name: Upstream and Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Git repository details
      run: |
        echo "Enter the URL of the base repository:"
        read base_repo_url
        echo "Enter the branch of the base repository:"
        read base_branch
        echo "Enter the URL of the port repository:"
        read port_repo_url
        echo "Enter the branch of the port repository:"
        read port_branch
        echo "Enter the name of the artifact:"
        read artifact_name
      
    - name: Checkout base code
      uses: actions/checkout@v2
      with:
        repository: ${{ base_repo_url }}
        ref: ${{ base_branch }}
      
    - name: Set up Git user
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
      
    - name: Push commits to port repository
      run: |
        git remote add port_repo ${{ port_repo_url }}
        git checkout -b port_branch
        git push port_repo port_branch
      
    - name: Zip ported directory
      run: zip -r ${{ artifact_name }}.zip .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ artifact_name }}
        path: ${{ artifact_name }}.zip
